require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - vendor/**/*

Rails:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable
    - start_of_line

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive
