language: ruby
cache: bundler
sudo: required

rvm:
  - 2.3.0

before_install:
  - gem install bundler -v 1.13.6
  - bin/compile

script:
  - bin/ci

after_success:
  - bundle exec codeclimate-test-reporter
