language: ruby
cache: bundler
sudo: required

os:
  - linux
  - osx

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.3
  - 2.4.0

before_install:
  - gem install bundler
  - bin/compile

script:
  - bin/ci

after_success:
  - bundle exec codeclimate-test-reporter
